name: depi_generator
description: The code generator for the depi dependency injection library.
version: 1.0.0
repository: https://github.com/tomasweigenast/depi
issues: https://github.com/tomasweigenast/depi/issues

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  dart_style: ^2.3.6
  depi: ^1.0.0
  glob: ^2.1.2
  path: ^1.9.0
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.9
  lint: ^2.3.0
  test: ^1.24.0

dependency_overrides:
  depi:
    path: ../depi
