name: depi
description: Dart and Flutter dependency injection library.
version: 1.0.0
repository: https://github.com/tomasweigenast/depi
issues: https://github.com/tomasweigenast/depi/issues

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lint: ^2.3.0
  lints: ^3.0.0
  test: ^1.24.0
