name: depi
description: Dart and Flutter efficient dependency injection library with code generation
version: 1.1.0
repository: https://github.com/tomasweigenast/depi
issues: https://github.com/tomasweigenast/depi/issues

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
