name: example
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  depi: any
  depi_generator:
    path: ../

dev_dependencies:
  build_runner: ^2.4.9

dependency_overrides:
  depi:
    path: ../../depi
