// THIS WAS GENERATED BY depi_generator. DO NOT EDIT.

part of 'service_collection.dart';

abstract base class _$MyServiceProvider extends ServiceCollection {
  _$MyServiceProvider._production() {
    putTransient<AbstractService>((services) => ConcreteA());
    putSingleton<ServiceB>((services) => ServiceBImplementation());
    putSingleton<ServiceE>((services) => ServiceE());
    putSingleton<ServiceD>((services) => ServiceDImplementation());
    putSingleton<ServiceC>((services) => ServiceC(
          serviceE: services(),
          serviceD: services(),
          options: services(),
        ));
  }
  _$MyServiceProvider() {
    putSingleton<ServiceA>((services) => ServiceA());
    putSingleton<ServiceB>((services) => ServiceB());
    putSingleton<ServiceE>((services) => ServiceE());
  }

  void configureServices(ServiceProvider serviceProvider);

  @override
  ServiceProvider build() {
    final serviceProvider = super.build();
    configureServices(serviceProvider);
    return serviceProvider;
  }
}
