// THIS WAS GENERATED BY depi_generator. DO NOT EDIT.

part of 'service_collection.dart';

abstract base class _$MyServiceCollection extends ServiceCollection {
  _$MyServiceCollection._development() {
    putSingleton<AuthService>((services) => MockAuthService());
    putTransient<AbstractService>((services) => ConcreteB());
    putSingleton<ServiceD>((services) => ServiceDImplementation());
  }
  _$MyServiceCollection._production() {
    putSingleton<AuthService>((services) => ProductionAuthService());
    putTransient<AbstractService>((services) => ConcreteA());
    putSingleton<ServiceB>((services) => ServiceBImplementation());
    putSingleton<ServiceE>((services) => ServiceE());
    putSingleton<ServiceD>((services) => ServiceDImplementation());
    putSingleton<ServiceC>((services) => ServiceC(
          serviceE: services(),
          serviceD: services(),
          options: services(),
        ));
  }
  _$MyServiceCollection() {
    putSingleton<ServiceA>((services) => ServiceA());
    putSingleton<ServiceB>((services) => ServiceB());
    putSingleton<ServiceE>((services) => ServiceE());
  }
  void configureServices(ServiceProvider serviceProvider);
  @override
  ServiceProvider build() {
    final serviceProvider = super.build();
    configureServices(serviceProvider);
    return serviceProvider;
  }
}
